#ifndef COMMON_STDAFX_H_
#define COMMON_STDAFX_H_

#ifdef _MSC_VER
// disable portability warnings generated by 
// pointer arithmetic in code
#pragma warning( disable : 4996 )
#define _CRT_SECURE_NO_DEPRECATE
#endif 

#ifdef _WIN32
#pragma once
#define WIN32_LEAN_AND_MEAN		// Exclude rarely-used stuff from Windows headers

#include <windows.h>
#endif

#include <xmmintrin.h>
#include <malloc.h>
#include <math.h>
#include <iostream>
#include <vector>
#include <hash_map>

#endif // COMMON_STDAFX_H_