##############################################################################
# GLVU EXAMPLES MAKEFILE
##############################################################################
BASE_DIR=..
TYPE=Lib
LIB_NAME = Mgc 
LIB_SRCS = MgcAppr3DGaussPointsFit.cpp MgcBox3.cpp MgcCont3DBox.cpp MgcEigen.cpp MgcMath.cpp MgcMatrix3.cpp MgcQuaternion.cpp MgcVector3.cpp MgcPlane.cpp\
MgcCont3DMinBox.cpp MgcMinimizeND.cpp MgcMinimize1D.cpp 

PUBLIC_HEADERS = MagicFMLibType.h   MgcCont3DBox.h MgcMath.inl    MgcRTLib.h\
MgcAppr3DGaussPointsFit.h  MgcEigen.h      MgcMatrix3.h     MgcVector3.h\
MgcBox3.h                  MgcEigen.inl    MgcMatrix3.inl   MgcVector3.inl\
MgcBox3.inl                MgcMath.h       MgcQuaternion.h MgcPlane.h MgcPlane.inl\
MgcCont3DMinBox.h	MgcMinimize1D.h    MgcMinimize1D.inl MgcMinimizeND.h MgcMinimizeND.inl
WITH_FEATURES := 

include $(BASE_DIR)/Ubermake.defs


